name: CI

on:
  push:
    branches: "master"
    tags: "v*"
  pull_request:
    branches: "master"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: docker build . -f test.Dockerfile -t "test/test:test"
